apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-producer
  serviceName: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: simple-kafka-producer
        image: satchpx/simple-kafka-producer:0.1
        imagePullPolicy: Always
        command: [ "/bin/sleep"]
        args: ["infinity" ]
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: kafka-producer
