apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-consumer
  labels:
    app: kafka-consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-consumer
  serviceName: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: simple-kafka-consumer
        image: satchpx/kafka-consumer:0.1
        imagePullPolicy: Always
        command: [ "/bin/sleep"]
        args: ["infinity" ]
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer
  labels:
    app: kafka-consumer
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: kafka-consumer
