apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-consumer
  labels:
    app: kafka-consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: simple-kafka-consumer
        image: satchpx/simple-kafka-producer:0.1
        imagePullPolicy: Always
        command: [ "tail -f /dev/null" ]
