#!/usr/bin/env bash

# @TODO: Roll these into cmdline args
topic='test'
num_records='100000'
record_size='10000'

cnt=$(kafka-topics --zookeeper confluent-cp-zookeeper.confluent:2181 --list | grep ${topic} | wc -l )

if [ "${cnt}" -eq 0 ]; then
    # create a topic
    kafka-topics \
        --zookeeper confluent-cp-zookeeper.confluent:2181 \
        --create --topic ${topic} \
        --partitions 6 \
        --replication-factor 3
fi

# Generate and write dummy data
while true; do
    kafka-producer-perf-test \
        --topic ${topic} \
        --num-records ${num_records} \
        --record-size ${record_size} \
        --throughput -1 \
        --producer-props acks=1 \
        bootstrap.servers=confluent-cp-kafka.confluent:9092
    sleep 60
done