#!/usr/bin/env bash

POD_ID=`echo ${MY_POD_NAME} | cut -d- -f3`
TOPIC=test-${POD_ID}

# Create the topic
kafka-topics --create --topic ${TOPIC} \
    --replication-factor 3 \
    --partitions 3 \
    --zookeeper confluent-cp-zookeeper.confluent:2181

# Run the producer
kafka-verifiable-producer --topic ${TOPIC} \
    --broker-list confluent-cp-kafka-headless.confluent:9200 \
    --max-messages 100000000 \
    --repeating-keys 100